name: Pull request - CI

on:
  workflow_dispatch:
  push:
    paths:
     - 'src/**'
    branches: [ main ]

  pull_request:
    paths:
     - 'src/**'
    branches: [ main ]

permissions:
  contents: write
  security-events: write
  actions: read
  packages: read
  pull-requests: write

jobs:
  SAST:
    name: SAST - codeql
    runs-on: ubuntu-latest

    strategy:
          fail-fast: false
          matrix:
            include:
            - language: python
              build-mode: none
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended
  
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          upload: true

  SCA:
    name: SCA - Python dependencies
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
          vulnerability-check: true

  Container_security:
    name: Dockerfile Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: |
          docker build -f src/Dockerfile -t test-image src/

      - name: Image Scan
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: test-image
          fail-build: true
          severity-cutoff: high

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: container-scan-sarif
          path: ${{ steps.scan.outputs.sarif }}
          retention-days: 1
