name: Pull request - CI

on:
  pull_request:
    paths:
     - 'src/**'
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  SCA:
    name: SCA - Python dependencies
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        comment-summary-in-pr: true
        vulnerability-check: true

  Container_security:
    name: Dockerfile Scan
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    
    - name: Build image
      run: |
        docker build -f src/Dockerfile -t test-image src/

    - name: Image Scan
      uses: anchore/scan-action@v6
      id: scan
      with:
        image: test-image
        fail-build: false
        severity-cutoff: high

    - uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
